### ISSUE TITLE
Suppress errors?

### ISSUE THREAD

**Issue by joinemm** [hugolgst/vimsence#19]
Opening vim while this plugin is installed, and discord isnt running, gets me an annoying error
`[discord] local discord client not found`

As I don't always have discord running, I would prefer if it just silently failed when discord isn't found.

Also `[discord] pidfile exists` when i open multiple instances of vim

**Comment by LunarWatcher** [comment]
What OS? No parts of the plugin responds like that

**Comment by joinemm** [comment]
Sorry my bad, I found the cause to be a another plugin
