### ISSUE TITLE
Add support for tsx and jsx?

### ISSUE THREAD

**Issue by MonliH** [hugolgst/vimsence#21]
It would be nice if there were icons for `jsx` and `tsx`. The filetypes for the `jsx` and `tsx` in vim are `javascriptreact` and `typescriptreact`, respectively.

I tried to add these filetypes to the mapping (see my [fork](https://github.com/MonliH/vimsence)), but it didn't change anything. How would I go about doing this?

**Comment by LunarWatcher** [comment]
Adding images is done in the discord app itself. You'll either need to make your own app (https://discord.com/developers/applications), or get hugolgst (the owner of the default app) to add the images.

**Comment by MonliH** [comment]
Oh, I was suggesting that `jsx` and `tsx` don't even need a new icon. They could just use the `ts` and `js` icons. Hence why I tried to change the mappings in my fork.

Now that you bring that up, though, it _would_ be nice to have seperate icons for them, although in my opinion the `ts` and `js` ones would work fine. (There isn't really a tsx logo)

**Comment by hugolgst** [comment]
I will try to review the PR a little bit later sorry for the delay.

**Comment by MonliH** [comment]
PR? I still haven't gotten it to work in my branch.

**Comment by LunarWatcher** [comment]
This might actually be a bug instead. Something doesn't make sense, but I'm not sure what yet. I'll need to run some local tests

**Comment by MonliH** [comment]
I'll test this after that PR gets merged, thanks!
