### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by eruizc-dev** [hugolgst/vimsence#33]
I've seen many filetypes that just show an `?` icon or an incorrect icon. Here I list all I've seen missing:

| Filetype | Current | Expected | Extensions |
| -- | -- | -- | -- |
| Sql | None | Sql | `.sql` |
| Plsql | None | Plsql | `.plsql` |
| JavascriptReact | Javascript | JavascriptReact | `.jsx` |
| TypescriptReact | Typescript | TypescriptReact | `.tsx` |
| Brainfuck | None | Brainfuck | `.bf` |
| C Header | C++ | C | `.h` |
| Fortran | None | Fortran | `.f`, `.for`, `.f90`, `.f95`, `.f03` |

**Comment by eruizc-dev** [comment]
@hugolgst I already added support for most of them, do you want me to do a single PR for the entire issue or make them separate?

**Comment by hugolgst** [comment]
As it works better for you

**Comment by hugolgst** [comment]
I will check the PR this evening, thanks :)

**Comment by adityaxdiwakar** [comment]
Any update on this?

**Comment by hugolgst** [comment]
I’m gonna do it a bit later if it works for you
