### ISSUE TITLE
Change the LaTeX logo

### ISSUE THREAD

**Issue by agentfire170** [hugolgst/vimsence#37]
Edit: I just realized that in some instances, there is a very dark background for discord, which would make a transparent-background logo look bad as well. Is there a way to change the logo so the background of the image fills the frame?

The LaTeX logo has a white trim around it, which looks bad when viewing Discord using dark mode. Please change the file to one that has a transparent background, like [this](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.freebiesupply.com%2Flogos%2Flarge%2F2x%2Flatex-logo-png-transparent.png&f=1&nofb=1)

**Comment by hugolgst** [comment]
Done
