### ISSUE TITLE
How to actually add custom icons? 

### ISSUE THREAD

**Issue by harisahmed05** [hugolgst/vimsence#59]
I did this to add Erlang icon but it's not working,
`let g:vimsense_custom_icons = {'erlang': '/home/shanto/Pictures/erlang.png'}
`
Any solution? Is 'iconname' should actually be the icon location?

**Comment by harisahmed05** [comment]
I also tried using .ico(64x64) file. Converted .png though online icon converter. But still, doesn't work. :(

**Comment by hugolgst** [comment]
Hi, it doesn't work like this unfortunately.
If you use our version we have to add it in the Discord Application. 

If you want to handle the icons yourself, create a Discord Application and replace the Client ID in the code.
