### ISSUE TITLE
Request for more language icons or a description of how a user could add their own

### ISSUE THREAD

**Issue by jcarter777** [hugolgst/vimsence#8]
There are a lot of languages which show as a grey question mark in the game activity display such as Assembly (.asm | .S) and Java (.java), it would be nice if these had icons or if instructions on how to add icons for them were included somewhere. Apologies if I'm missing something.

**Comment by ananagame** [comment]
yeah actually you can’t add your own icons because it is relative to the discord application, I will as them as quickly as possible

**Comment by void-777** [comment]
Hey thanks for responding, I dont understand what you mean when you say _I_ can't add my own icons but then go on to say that _you_ will add them as quickly as possible. I noticed in the repo that they weren't local image files but If you can add them then surely I can?

**Comment by ananagame** [comment]
It is a Discord Application on my account so you can create your app but you will need to add all the icons

**Comment by jason-shepherd** [comment]
I know I'm a bit late to the party, but would it be possible to differentiate the icons of neovim and vim? Just wondering.

**Comment by ananagame** [comment]
You must create another Discord application to do this @jason-shepherd

**Comment by ananagame** [comment]
and just replace the ID in the code
